name: Dev Build

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

jobs:
  dev-build:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: dev

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set current date as env variable
        run: echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BUILD_DATE=${{ env.NOW }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ env.APP_VERSION }}.${{ github.run_number }}
          tags: ${{ github.repository }}:${{ env.APP_VERSION }}.${{ github.run_number }}
          push: false
          load: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ssllabs-scan:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ssllabs-scan:buildcache,mode=max

      - name: Run
        run: >
          docker run --rm --name ssl-scanner
          ${{ github.repository }}:${{ env.APP_VERSION }}.${{ github.run_number }} 
          -usecache https://www.google.com

      - name: Push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BUILD_DATE=${{ env.NOW }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ env.APP_VERSION }}.${{ github.run_number }}
          tags: ${{ github.repository }}:${{ env.APP_VERSION }}.${{ github.run_number }}
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ssllabs-scan:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ssllabs-scan:buildcache,mode=max
